### ISSUE TITLE
Remove R926

### ISSUE THREAD

**Issue by gituser789** [upb-lea/LCB-CCB-01_LEA_Control_Board#10]
R926 is for turn on/off the C929.
It makes no difference to desolder R926 or C929, so R926 can be removed from the circuit.

![image](https://github.com/user-attachments/assets/676fa768-1323-4e6e-bd9c-d089d68e6046)

**Comment by VijayThera** [comment]
Removed R926

![image](https://github.com/user-attachments/assets/74f9d467-eceb-41f9-a76f-3d5d49bd6b7d)
