### ISSUE TITLE
U902 Input Voltage range

### ISSUE THREAD

**Issue by gituser789** [upb-lea/LCB-CCB-01_LEA_Control_Board#11]
Common mode input voltage range is not enough.

![image](https://github.com/user-attachments/assets/2eaba32a-693a-4b75-aac9-c3b7ddd33188)

**Comment by gituser789** [comment]
* [ ] check needed current from analog part of the controller
* [ ] check provided current from LDO
* [ ] Remove the buffer

**Comment by VijayThera** [comment]
**Removed buffer U902** 
![image](https://github.com/user-attachments/assets/339f00ff-38c9-462c-be6c-cf4e82538eb8)


needed current for analog part of the controller - Max. 20 mA
![image](https://github.com/user-attachments/assets/31a50217-d977-4aa8-bb9f-267d33d89618)


provided current from LDO - Typ. ~ 30 mA
![image](https://github.com/user-attachments/assets/6faf656e-6d4a-4c67-bf0d-2f88ff7fa1f5)
