### ISSUE TITLE
connect A16 of the main controller (F2838x) to an testport for clock output

### ISSUE THREAD

**Issue by e-i-s-e** [upb-lea/LCB-CCB-01_LEA_Control_Board#3]
GPIO73 of the main controller F2838x (U703) can serve as an clock output.
This pin is not connected yet (NC). It should, at least, be connected to a test pin for debugging.

**Comment by VijayThera** [comment]
GPIO73 is already connected to the left connectors
![image](https://github.com/user-attachments/assets/537b2b0c-80c8-4800-8266-eae35d8e116c)
