### ISSUE TITLE
ADC filters should not be in series

### ISSUE THREAD

**Issue by gituser789** [upb-lea/LCB-CCB-01_LEA_Control_Board#7]
# Description of failure
Filtering for ADC and error comparator are in series. This leads to unwanted linking in filter time constants and also in filter functionality, because the first filter resistor limits the current for the second filter. This results in an unwanted input signal for the input comparator.

# Workaround
The workaround is to bring the filter values to uncritical values (r1=100, c1=1n, r2=2k2, c2=1n). 

# Real fix
The final solution is a schematic change in placing the filters in parallel, not in series.

- [ ] Replace filter values for the comparator inputs
- [ ] update schematic to the new values

**Comment by VijayThera** [comment]
Updated schematics with parallel connection

![image](https://github.com/user-attachments/assets/e0b9a453-6fb7-4ce8-8aab-bc0d3afb54bb)
![image](https://github.com/user-attachments/assets/f38a6d71-cf33-42c3-aba3-9c730ae3717f)
